CFG = {
    DEBUG="true",
    MONITOR_SIDE="back",
    MODEM_SIDE="top",
    LEVER_SIDE="back",
    BLINKING_SIDE="front",
    DEVICES={
        speaker="left",
        monitor="monitor_13",
        infusionPedestal0="mysticalagriculture:infusion_pedestal_5",
        infusionPedestal1="mysticalagriculture:infusion_pedestal_4",
        infusionPedestal2="mysticalagriculture:infusion_pedestal_3",
        recycleInventory="minecraft:chest_1"
    },
    PROTO={
        GET_MAINFRAME="Casino/mainframe/get",
        USER={
            NEW="Casino/user/new",
            INFO="Casino/user/info",
            TRANSACTION={
                SUBTRACT="Casino/user/transaction/subtract",
                ADD="Casino/user/transaction/add"
            }
        }
    },
    FILES={
        USERID="disk/userid.dat",
        LOGON="disk/logon.dat"
    },
    GAME={
        MIN_BET=10
    }
}