CFG = {
    DEBUG="true",
    MODEM_SIDE="top",
    CABLE_SIDE="back",
    CABLE={
        speaker="speaker_2",
        monitor_input="monitor_1",
        monitor_bets="monitor_3",
        monitor_spinner="monitor_2",
        monitor_wheel="monitor_11"
    },
    PROTO={
        GET_MAINFRAME="Casino/mainframe/get",
        USER={
            NEW="Casino/user/new",
            INFO="Casino/user/info",
            TRANSACTION={
                SUBTRACT="Casino/user/transaction/subtract",
                ADD="Casino/user/transaction/add"
            }
        }
    },
    FILES={
        PLAYER_1={
            USERID="disk/userid.dat",
            LOGON="disk/logon.dat"
        },
        PLAYER_2={
            USERID="disk2/userid.dat",
            LOGON="disk2/logon.dat"
        },
        PLAYER_3={
            USERID="disk3/userid.dat",
            LOGON="disk3/logon.dat"
        },
        PLAYER_4={
            USERID="disk4/userid.dat",
            LOGON="disk4/logon.dat"
        },
    },
    GAME={
        MAX_PLAYERS=4,
        WHEEL_STEPS_MIN=50,
        WHEEL_STEPS_MAX=100
    }
}